/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConceptEditorialRouteImport } from './routes/concept-editorial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardDothtmlRouteImport } from './routes/dashboard[.]html'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PricingDothtmlRouteImport } from './routes/pricing[.]html'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SigninDothtmlRouteImport } from './routes/signin[.]html'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TogglesRouteImport } from './routes/toggles'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as IntegrationsSlugRouteImport } from './routes/integrations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptEditorialRoute = ConceptEditorialRouteImport.update({
  id: '/concept-editorial',
  path: '/concept-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDothtmlRoute = DashboardDothtmlRouteImport.update({
  id: '/dashboard.html',
  path: '/dashboard.html',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingDothtmlRoute = PricingDothtmlRouteImport.update({
  id: '/pricing.html',
  path: '/pricing.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninDothtmlRoute = SigninDothtmlRouteImport.update({
  id: '/signin.html',
  path: '/signin.html',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TogglesRoute = TogglesRouteImport.update({
  id: '/toggles',
  path: '/toggles',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareRoute,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompareRoute,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const IntegrationsSlugRoute = IntegrationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IntegrationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRouteWithChildren
  '/concept-editorial': typeof ConceptEditorialRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard.html': typeof DashboardDothtmlRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/pricing.html': typeof PricingDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin.html': typeof SigninDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/toggles': typeof TogglesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/compare/': typeof CompareIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/concept-editorial': typeof ConceptEditorialRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard.html': typeof DashboardDothtmlRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/pricing.html': typeof PricingDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin.html': typeof SigninDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/toggles': typeof TogglesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/compare': typeof CompareIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRouteWithChildren
  '/concept-editorial': typeof ConceptEditorialRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard.html': typeof DashboardDothtmlRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/pricing.html': typeof PricingDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin.html': typeof SigninDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/terms': typeof TermsRoute
  '/toggles': typeof TogglesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/compare/': typeof CompareIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/compare'
    | '/concept-editorial'
    | '/contact'
    | '/dashboard'
    | '/dashboard.html'
    | '/faq'
    | '/features'
    | '/glossary'
    | '/guide'
    | '/integrations'
    | '/onboarding'
    | '/pricing'
    | '/pricing.html'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signin.html'
    | '/sitemap.xml'
    | '/story'
    | '/terms'
    | '/toggles'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/integrations/$slug'
    | '/compare/'
    | '/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/concept-editorial'
    | '/contact'
    | '/dashboard'
    | '/dashboard.html'
    | '/faq'
    | '/features'
    | '/glossary'
    | '/guide'
    | '/onboarding'
    | '/pricing'
    | '/pricing.html'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signin.html'
    | '/sitemap.xml'
    | '/story'
    | '/terms'
    | '/toggles'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/integrations/$slug'
    | '/compare'
    | '/integrations'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/compare'
    | '/concept-editorial'
    | '/contact'
    | '/dashboard'
    | '/dashboard.html'
    | '/faq'
    | '/features'
    | '/glossary'
    | '/guide'
    | '/integrations'
    | '/onboarding'
    | '/pricing'
    | '/pricing.html'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signin.html'
    | '/sitemap.xml'
    | '/story'
    | '/terms'
    | '/toggles'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/integrations/$slug'
    | '/compare/'
    | '/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CompareRoute: typeof CompareRouteWithChildren
  ConceptEditorialRoute: typeof ConceptEditorialRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DashboardDothtmlRoute: typeof DashboardDothtmlRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  GlossaryRoute: typeof GlossaryRoute
  GuideRoute: typeof GuideRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PricingDothtmlRoute: typeof PricingDothtmlRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SigninDothtmlRoute: typeof SigninDothtmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  TermsRoute: typeof TermsRoute
  TogglesRoute: typeof TogglesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept-editorial': {
      id: '/concept-editorial'
      path: '/concept-editorial'
      fullPath: '/concept-editorial'
      preLoaderRoute: typeof ConceptEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard.html': {
      id: '/dashboard.html'
      path: '/dashboard.html'
      fullPath: '/dashboard.html'
      preLoaderRoute: typeof DashboardDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing.html': {
      id: '/pricing.html'
      path: '/pricing.html'
      fullPath: '/pricing.html'
      preLoaderRoute: typeof PricingDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin.html': {
      id: '/signin.html'
      path: '/signin.html'
      fullPath: '/signin.html'
      preLoaderRoute: typeof SigninDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toggles': {
      id: '/toggles'
      path: '/toggles'
      fullPath: '/toggles'
      preLoaderRoute: typeof TogglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof CompareRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/$slug': {
      id: '/integrations/$slug'
      path: '/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof IntegrationsSlugRouteImport
      parentRoute: typeof IntegrationsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CompareRouteChildren {
  CompareSlugRoute: typeof CompareSlugRoute
  CompareIndexRoute: typeof CompareIndexRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareSlugRoute: CompareSlugRoute,
  CompareIndexRoute: CompareIndexRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

interface IntegrationsRouteChildren {
  IntegrationsSlugRoute: typeof IntegrationsSlugRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsSlugRoute: IntegrationsSlugRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CompareRoute: CompareRouteWithChildren,
  ConceptEditorialRoute: ConceptEditorialRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DashboardDothtmlRoute: DashboardDothtmlRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  GlossaryRoute: GlossaryRoute,
  GuideRoute: GuideRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PricingDothtmlRoute: PricingDothtmlRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SigninDothtmlRoute: SigninDothtmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  TermsRoute: TermsRoute,
  TogglesRoute: TogglesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
